### ISSUE TITLE
Wiping creds

### ISSUE THREAD

**Issue by shano** [nicrivard/readwise2directory#1]
Hey!

Was just looking through the repo. I'd highly recommend you run this against your codebase asap:
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/removing-sensitive-data-from-a-repository

Unfortunately just because you remove a file from git with a commit doesn't mean it's gone forever. I see credentials in there you definitely want to change ASAP too(any anywhere else you might use those creds).

You can still access the file here:

**link removed**

**Comment by nicrivard** [comment]
Oh my! Thank you for the heads-up @shano ! This is my first time working seriously with GitHub - sounds like I committed (no pun intended) a rookie error :o 

I've followed the approach recommended, changed my passwords, and created a new "master" branch with the original files as the first commit, and deleted the old "main" branch. 

Please can you check if you can still access my old commits as I can only do so via the link in your issue above, but not on the main repository page...

Thank you in advance for your help with this.

**Comment by shano** [comment]
Hi @nicrivard no worries! I'll remove that link. I can't see a commit anymore myself that should retain the credentials.. 

Only trouble you have is the forks from your repo still contain the file, so as long as you're safe from any hack I think you're good!
