### ISSUE TITLE
.CSV VS .MD export/import

### ISSUE THREAD

**Issue by jameslashmar** [nicrivard/readwise2directory#6]
Less of an issue and more of a feature request (if possible).

Whilst testing the Readwise export functionality between having this script work, I have a bunch of my books in Obsidian using the markdown export. Whilst the script does a lovely job of layout etc and import, one thing I would like to see personally that you get with the markdown export is a preview of the book cover itself. 

Here's a screenshot of the script's .CSV vs manual .MD export/import result.

What do you think?

![image](https://user-images.githubusercontent.com/25590698/104914749-7eef4880-5987-11eb-8ef5-c08a62f93fb8.png)

**Comment by nicrivard** [comment]
Ooh I like your thinking @jameslashmar 💡 let me see what I can do 👍

**Comment by nicrivard** [comment]
@jameslashmar Added `cover image` functionality as part of [release v1.5](https://github.com/nicrivard/readwise2directory/releases/tag/v1.5) 🎨

**Comment by jameslashmar** [comment]
This works perfectly, thank you!

Now we just need Audible to sync properly to Readwise 😂
