### ISSUE TITLE
Update readwiseMetadata.py to be windows friendly

### ISSUE THREAD

**Issue by jameslashmar** [nicrivard/readwise2directory#8]
Last one I promise! Less of an issue, more documentation update.

So, today I set up a task in windows to automate this script. Up until now, Chromedriver has been prompting me for the download.   I managed to halt the process and look in chrome and see the download location was mangled.  The was due to my downloads folder being `\readwiseDownloads` in the metadata file. 

Now, for all the other strings I have in the file, they were fine. As this contains the `\r`, escape in python, it was messing things up.  Now, a way around that is to use forward slashes in the Windows paths.  However, Chrome doesn't like this and fails on the download.  

The simple solution is to use a double backslash in the Windows paths, i.e. `\\.obsidian\\readwiseDownloads` . These also do not need terminating with a final slash or double slash. 

It would be nice just to include a comment in this file for people that maybe aren't as code savvy for the Windows users 👍

I know have this running every 3 days, like a dream!

Thanks again!

**Comment by nicrivard** [comment]
Thank you for the feedback @jameslashmar ! 

I've [updated the comments](https://github.com/nicrivard/readwise2directory/commit/d1b1adcef4d5b594e54629a054f3f848d40754d4) in `readwiseMetadata.py` to make it clearer to use '\\\\' for Windows users, and it will be part of the next release.

Ooh would you mind sharing your script (or steps) with me? 🙏

**Comment by jameslashmar** [comment]
So i created a task to run every 3 days and terminate if it lasts longer than an hour

The settings in red make it silent

![image](https://user-images.githubusercontent.com/25590698/105366079-d47d5c80-5bf6-11eb-8037-12308fefceb3.png)


Then these are the parameters I use to execute your script :)


![image](https://user-images.githubusercontent.com/25590698/105366013-c596aa00-5bf6-11eb-8539-d7a36ad94aa9.png)
