### ISSUE TITLE
Chrome / WebDriver Optimisation & Performance

### ISSUE THREAD

**Issue by jameslashmar** [nicrivard/readwise2directory#9]
Would it be possible to run the WebDriver as headless to avoid Chrome grabbing attention?

Looks like it's possible here. I think there might be something in the last post here:
https://stackoverflow.com/questions/53657215/running-selenium-with-headless-chrome-webdriver

I think disabling the GPU extensions might be worth toying with too.

I also adjusted my Scheduled Task in Windows to run the script silently. See here:
https://pureinfotech.com/prevent-command-window-appearing-scheduled-tasks-windows-10/

I'm sure this is possible on macOS too.

Just a thought!

**Comment by nicrivard** [comment]
Yeah for some reason no matter what I tried running the WebDriver headless didn't seem to work when fetching tags in bulk via CSV download (hence # on line 579), but it does work when fetching tags individually (line 213). 

I'll keep trying as I agree with you, it would be awesome for everything to run silently in the background! Let me know if you're able to figure it out before me

**Comment by nicrivard** [comment]
@jameslashmar I'm very happy to say that I've managed to fix my code to enable the script to run completely in the background! The magic of these three lines of code means we don't need the `waitForDownloadAndRename` function or chrome://downloads:

```
driver.command_executor._commands["send_command"] = ("POST", '/session/$sessionId/chromium/send_command')
params = {'behavior': 'allow', 'downloadPath': sourceDirectory}
driver.execute_cdp_cmd('Page.setDownloadBehavior', params)
```

This also means we no longer need to specify a `downloadsDirectory` field in the `readwiseMetadata.py` file. 

I've updated both files in the latest [release v1.7](https://github.com/nicrivard/readwise2directory/releases/tag/v1.7)

**Comment by jameslashmar** [comment]
Amazing!! Just pulled the latest, works like a charm! Thanks!
